export const ACTION_LIST_POST = 'ACTION_LIST_POST'
export const ACTION_COUNT = 'ACTION_COUNT'
export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const INSERT_AUTH = 'INSERT_AUTH'
export const LOAD_PARENT_CATE = 'LOAD_PARENT_CATE'