export const CHANGE_X = 'CHANGE_X'
export const LIST_POST = 'LIST_POST'
export const COUNT = 'COUNT'
export const CHANGE_TOKEN = 'CHANGE_TOKEN'
export const CHANGE_IS_AUTHEN = 'CHANGE_IS_AUTHEN'
export const CHANGE_CATE = 'CHANGE_CATE'
export const CHANGE_RELEASE = 'CHANGE_RELEASE'
