export const CHANGE_X = 'CHANGE_X'
export const LIST_POST = 'LIST_POST'
export const COUNT = 'COUNT'
export const CHANGE_TOKEN = 'CHANGE_TOKEN'
export const CHANGE_IS_AUTHEN = 'CHANGE_IS_AUTHEN'
export const LOAD_PARENT_CATE = 'LOAD_PARENT_CATE'
